### ISSUE TITLE
Default Backend Displays Cloudflare Challenge

### ISSUE THREAD

**Issue by zans-laksa** [scandipwa/create-scandipwa-app#67]
Installed the clean SPWA with CSA.
Default proxy is pointing to https://40kskudemo.scandipwa.com
After the start all graphql requests fail. The response can be seen on the screenshot.

40kskudemo works fine, graphql responds with json.

![image](https://user-images.githubusercontent.com/73945186/127380686-777b9d2b-1c0e-4895-bb3e-d1733f374fd2.png)

**Comment by zans-laksa** [comment]
The issue has been solved on the cloud flare level.

**Comment by nnirmana** [comment]
![image](https://user-images.githubusercontent.com/88105283/127866524-6c6abcb7-8f1f-4664-8a2b-467fb0fea536.png)

It seems issue is still not fixed
